payment/urls.py
from django.urls import path
from . import views


app_name = 'payment'

urlpatterns = [
    path('success/', views.pay_success, name='successed_payment'),
    path('cancelled/', views.cancelled, name='cancelled_payment'),
    path('<int:box_pk>', views.make_payment, name='make_payment'),
]

self_storage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('authorization.urls')),
    path('accounts/', include('allauth.urls')),
    path('payment/', include('payment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='main'),
    path('boxes/', views.boxes, name='boxes'),
    path('my_rent/', views.my_rent, name='my_rent'),
    path('faq/', views.faq, name='faq'),
    path('logout/', views.log_out, name='log_out'),
    path('<int:box_id>', views.send_qr, name='send_qr'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User


class Application(models.Model):
    email_adress = models.EmailField(default='Почта пользователя', verbose_name='Почта пользователя')

    def __str__(self):
        return self.email_adress


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='customer')
    photo = models.ImageField(verbose_name='Фото пользователя', null=True, blank=True)
    phone_number = models.CharField(null=True, blank=True, max_length=10, verbose_name='Телефон пользователя')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class Storage(models.Model):
    location_city = models.CharField(default='Москва', max_length=35, verbose_name='Город')
    location_street_name = models.CharField(default='Тверская', max_length=35, verbose_name='Улица')
    location_street_number = models.CharField(default='15', max_length=10, verbose_name='Идентификатор дома')
    store_temperature = models.DecimalField(verbose_name='Температура на складе', decimal_places=2, max_digits=5)
    ceiling_height = models.DecimalField(verbose_name='Высота потолка', decimal_places=2, max_digits=5)
    payment_per_month = models.IntegerField(verbose_name='Оплата за месяц')
    small_photo = models.ImageField(blank=True, verbose_name='Маленькое фото', default='image9.png')
    large_photo = models.ImageField(blank=True, verbose_name='Большое фото', default='image2.png')
    note = models.CharField(null=True, blank=True, max_length=35, verbose_name='Заметка')
    total_boxes = models.IntegerField(null=True)

    def __str__(self):
        return self.location_city


class Box(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Клиент', blank=True, null=True, related_name='rented_boxes')
    storage = models.ForeignKey(Storage, on_delete=models.CASCADE, verbose_name='Склад', related_name='boxes')
    number = models.CharField(max_length=20, verbose_name='Номер в базе данных')
    in_use = models.BooleanField(default=False, verbose_name='Занятость бокса')
    rental_start_time = models.DateTimeField(null=True, verbose_name='Время начала аренды', blank=True)
    rental_end_time = models.DateTimeField(null=True, verbose_name='Время окончания аренды', blank=True)
    level = models.IntegerField(verbose_name='Этаж')
    square = models.IntegerField(verbose_name='Площадь', null=True)
    volume = models.IntegerField(verbose_name='Объём', null=True)
    price = models.IntegerField(verbose_name='Цена')

    def __str__(self):
        return f'Бокс {self.number} склада {self.storage.location_city}'

store/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from store.models import Storage, Customer, Application, Box, User
from email_sender.email_sender import send_email, get_qr_code

import datetime
import pytz


def save_email_if_sent(request):
    email = request.GET.get('EMAIL1')
    if not email:
        return
    # save email if valid else pass


def index(request):
    save_email_if_sent(request)
    storage = Storage.objects.order_by('?').first()
    rented_boxes = len(storage.boxes.filter(in_use=True))
    free_boxes = storage.total_boxes - rented_boxes

    storage_data = {
        'city': storage.location_city,
        'street_name': storage.location_street_name,
        'street_number': storage.location_street_number,
        'temperature': storage.store_temperature,
        'ceiling_height': storage.ceiling_height,
        'payment_per_month': storage.payment_per_month,
        'image_url': storage.large_photo.url,
        'total_boxes': storage.total_boxes,
        'free_boxes': free_boxes
    }
    return render(request, 'index.html', context=storage_data)


def boxes(request):
    save_email_if_sent(request)
    storages = Storage.objects.prefetch_related('boxes')
    
    context = {'storages': {}}
    for storage in storages:
        free_boxes = storage.boxes.filter(in_use=False)
        context['storages'][storage.pk] = {
            'info': storage,
            'free_boxes': free_boxes,
            'boxes_vol_to_3': free_boxes.filter(volume__lt=3),
            'boxes_vol_to_10': free_boxes.filter(volume__lt=10),
            'boxes_vol_from_10': free_boxes.filter(volume__gte=10)
        }

    return render(request, 'boxes.html', context=context)


@login_required(login_url='sign_in')
def my_rent(request):

    username = request.user
    user = User.objects.get(username=username)
    customer = user.customer
    
    user_data = {
        'username': user.username,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'image_url': customer.photo.url if customer.photo else 'static/no_foto.png',
        'password': user.password,
        'email': user.email,
        'phone_number': customer.phone_number,
    }
    
    user_boxes = customer.rented_boxes.all()


    if not user_boxes:
        note = 'У вас еще нет аренды :( ' \
               'Но вы можете арендовать свой первый бокс  по  привлекательной цене прямо сейчас'
        user_data.update(note=note)
        return render(request, 'my-rent-empty.html', context=user_data)

    user_boxes_data = []
    timezone = 'Europe/Moscow'

    for box in user_boxes:
        time_now = datetime.datetime.now(pytz.timezone(timezone))
        rental_end_time = box.rental_end_time
        time_left = rental_end_time - time_now
        warning = True if time_left.days <= 5 else False

        storage = box.storage
        user_boxes_data.append(
            {
                'storage_number': storage.id,
                'storage_location_city': storage.location_city,
                'storage_location_street_name': storage.location_street_name,
                'storage_location_street_number': storage.location_street_number,
                'id': box.id,
                'number': box.number,
                'rental_start_time': box.rental_start_time,
                'rental_end_time': box.rental_end_time,
                'warning': warning
            }
        )

    

    user_data.update(user_boxes=user_boxes_data)
    return render(request, 'my-rent.html', context=user_data)


def faq(request):
    return render(request, 'faq.html')


@login_required(login_url='sign_in')
def payment(request):
    storage = Storage.objects.order_by('?').first()
    rented_boxes = len(storage.boxes.filter(in_use=True))
    free_boxes = storage.total_boxes - rented_boxes

    storage_data = {
        'city': storage.location_city,
        'street_name': storage.location_street_name,
        'street_number': storage.location_street_number,
        'temperature': storage.store_temperature,
        'ceiling_height': storage.ceiling_height,
        'payment_per_month': storage.payment_per_month,
        'image_url': storage.large_photo.url,
        'total_boxes': storage.total_boxes,
        'free_boxes': free_boxes
    }

    return render(request, 'index.html', context=storage_data)


@login_required(login_url='sign_in')
def log_out(request):
    logout(request)
    return redirect(index)


def send_qr(request, box_id):
    user = request.user
    user_email = user.email
    box = Box.objects.get(id=box_id)
    box_number = box.number
    storage = box.storage
    qr_code = get_qr_code(storage.id, box_number, user.id)
    message = 'Здравствуйте, благодарим за оформление заказа! Ваш qr-код с информацией находится ниже'

    send_email(user_email, 'Оплата бокса', message, qr_code)

    return render(request, 'my-rent.html')

store/templates/my-rent-empty.html
{% extends 'base_short.html' %}
{% load static %}


{% block title %}My rent{%endblock%}

{% block content %}

<main class="container mt-header">
	<div class="row" role="tablist">
		<div class="col-lg-3 d-flex flex-column nav nav-pills">
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_orange SelfStorage_tab active" id="LK-tab" data-bs-toggle="pill" data-bs-target="#LK" type="button" role="tab" aria-controls="LK" aria-selected="true">Личный кабинет</button>
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_grey SelfStorage_tab" id="Rent-tab" data-bs-toggle="pill" data-bs-target="#Rent" type="button" role="tab" aria-controls="Rent" aria-selected="false">Моя аренда</button>
			<a href="{% url 'faq' %}" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">FAQ</a>
			<a href="{% url 'log_out' %}" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">Выйти</a>
		</div>
		<div class="col-lg-9">
			<div class="card tab-content p-5">
				<div class="tab-pane fade show active" id="LK" role="tabpanel" aria-labelledby="LK-tab">
					<div class="row">
						<div class="col-12 col-sm-5 d-flex flex-column align-items-center">
							<img src="{{ image_url }}"  alt="" class="rounded-pill mb-3" width="60%">
							<h4>{{ first_name }} {{ last_name }}</h4>
						</div>
						<div class="col-12 col-sm-7 d-flex flex-column">
							<form>
								<label class="fs_24 SelfStorage_green ms-2" for="EMAIL">E-mail</label>
								<input type="email" name="EMAIL_EDIT" id="EMAIL" class="form-control fs_24 ps-2 SelfStorage__input" value={{ email }} disabled>
								<label class="fs_24 SelfStorage_green ms-2" for="PHONE">Телефон</label>
								<input type="tel" name="PHONE_EDIT" id="PHONE" class="form-control fs_24 ps-2 SelfStorage__input" value={{ phone_number }} disabled>
								
								<button type="submit" class="btn SelfStorage_green ps-1" id="save" style="display: none">Сохранить</button>
								<a type="button" class="btn SelfStorage_orange ps-1" id="edit">Редактировать</a><br>
								<a type="button" class="btn SelfStorage_orange ps-1" id="change_password" href="{% url 'change_password' %}">Сменить пароль</a>
								<script>
									document.getElementById('edit').addEventListener('click', e => {
										e.preventDefault()
										document.getElementById('EMAIL').disabled = false
										document.getElementById('PHONE').disabled = false
										document.getElementById('change_password').style.display = 'none'
										document.getElementById('edit').style.display = 'none'
										document.getElementById('save').style.display = 'inline-block'
									})
									document.getElementById('save').addEventListener('click', () => {
										setTimeout(() => {
											document.getElementById('EMAIL').disabled = true
											document.getElementById('PHONE').disabled = true
											document.getElementById('change_password').style.display = 'inline-block'
											document.getElementById('edit').style.display = 'inline-block'
											document.getElementById('save').style.display = 'none'
										}, 0)
									})
								</script>
							</form>
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="Rent" role="tabpanel" aria-labelledby="Rent-tab">
					<h1 class="fw-bold SelfStorage_green">Добрый день, {{ first_name }}</h1>
					<h4 class="SelfStorage_grey my-5">{{ note }}</h4>
					<div><a class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3" href="{% url 'boxes' %}">Арендовать бокс</a></div>
					<a href="{% url 'faq' %}" class="SelfStorage_orange">Нужна помощь?</a>
				</div>
			</div>
		</div>
	</div>
</main>
{%endblock%}

store/templates/my-rent.html
{% extends 'base_short.html' %}
{% load static %}


{% block title %}My rent{%endblock%}

{% block content %}

<main class="container mt-header">
	<div class="row" role="tablist">
		<div class="col-lg-3 d-flex flex-column nav nav-pills">
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_orange SelfStorage_tab active" id="LK-tab" data-bs-toggle="pill" data-bs-target="#LK" type="button" role="tab" aria-controls="LK" aria-selected="true">Личный кабинет</button>
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_grey SelfStorage_tab" id="Rent-tab" data-bs-toggle="pill" data-bs-target="#Rent" type="button" role="tab" aria-controls="Rent" aria-selected="false">Моя аренда</button>
			<a href="{% url 'faq' %}" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">FAQ</a>
			<a href="{% url 'log_out' %}" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">Выйти</a>
		</div>
		<div class="col-lg-9">
			<div class="card tab-content p-5">
				<div class="tab-pane fade show active" id="LK" role="tabpanel" aria-labelledby="LK-tab">
					<div class="row">
						<div class="col-12 col-sm-5 d-flex flex-column align-items-center">
							<img src="{{ image_url }}"  alt="" class="rounded-pill mb-3"  width="60%">
							<h4>{{ first_name }} {{ last_name }}</h4>
						</div>
						<div class="col-12 col-sm-7 d-flex flex-column">
							<form>
								<label class="fs_24 SelfStorage_green ms-2" for="EMAIL">E-mail</label>
								<input type="email" name="EMAIL_EDIT" id="EMAIL" class="form-control fs_24 ps-2 SelfStorage__input" value={{ email }} disabled>
								<label class="fs_24 SelfStorage_green ms-2" for="PHONE">Телефон</label>
								<input type="tel" name="PHONE_EDIT" id="PHONE" class="form-control fs_24 ps-2 SelfStorage__input" value={{ phone_number }} disabled>
								
								<button type="submit" class="btn SelfStorage_green ps-1" id="save" style="display: none">Сохранить</button>
								<a class="btn SelfStorage_orange ps-1" id="edit">Редактировать</a>
								<a type="button" class="btn SelfStorage_orange ps-1" id="change_password" href="{% url 'change_password' %}">Сменить пароль</a>
								<script>
									document.getElementById('edit').addEventListener('click', e => {
										e.preventDefault()
										document.getElementById('EMAIL').disabled = false
										document.getElementById('PHONE').disabled = false
										document.getElementById('change_password').style.display = 'none'
										document.getElementById('edit').style.display = 'none'
										document.getElementById('save').style.display = 'inline-block'
									})
									document.getElementById('save').addEventListener('click', () => {
										setTimeout(() => {
											document.getElementById('EMAIL').disabled = true
											document.getElementById('PHONE').disabled = true
											document.getElementById('change_password').style.display = 'inline-block'
											document.getElementById('edit').style.display = 'inline-block'
											document.getElementById('save').style.display = 'none'
										}, 0)
									})
								</script>
							</form>
						</div>
					</div>
				</div>
			
				<div class="tab-pane fade" id="Rent" role="tabpanel" aria-labelledby="Rent-tab">
					<h1 class="fw-bold SelfStorage_green mb-5">Добрый день, {{ first_name }}</h1>
					<a href="#" class="SelfStorage_orange">История аренды</a>
					{% for box in user_boxes %}
						{% if box.warning %}
						<h4 class="SelfStorage_grey my-3">Срок Вашей аренды подходит к концу :( </h4>
						<h4 class="SelfStorage_grey my-3">Вы можете продлить аренду или забрать вещи до {{ box.rental_end_time|date:'d M Y' }} включительно.</h4>
						{% endif %}
					<div class="mb-5">
						<h4 class="SelfStorage_green">Мой склад №{{ box.storage_number }}</h4>
						<h4>{{ box.storage_location_city }}, ул. {{ box.storage_location_street_name }}, д. {{ box.storage_location_street_number }}</h4>
						<h4 class="SelfStorage_green">Мой бокс</h4>
						<h4>№{{ box.number }}</h4>
						<h4 class="SelfStorage_green">Срок аренды</h4>
						<h4>{{ box.rental_start_time|date:'d M Y' }} - {{ box.rental_end_time|date:'d M Y' }}</h4>
						<div><a href="{% url 'payment:make_payment' box.id %}" class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_green SelfStorage__btn2_green mb-3">Продлить аренду</a></div>
						<div><button><a href="{% url 'send_qr' box.id %}" class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3">Открыть бокс</a></button></div>
						<h5>{{ qr_sent }}</h5>
						<a href="#" class="SelfStorage_orange">Нужна помощь?</a>
					</div>
                    {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
</main>
{%endblock%}